# url: https://cadmus-inc.github.io
# baseurl: /agency-jekyll-theme/

# Site settings
title: CADMUS
email: contact@cadmusanalytics.com
description: "AI Tools for EMS"


# Team names, titles and social links
people:
- name: Brad Greer
  pic: 1
  position: Founder
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #
- name: Kevin Ge
  pic: 2
  position: Founder
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #2

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: #
  - title: facebook
    url: #
  - title: stack-overflow
    url: #
  - title: bitbucket 
    url: #
  - title: github
    url: www.cadmusanalytics.com

# Postal address (add as many lines as necessary)
# address:
#   - line: 400 West Lake Ave NW
#   - line: Atlanta, GA 30318

# Build settings
markdown: kramdown
permalink: pretty
