# url: https://cadmus-inc.github.io
# baseurl: /agency-jekyll-theme/

# Site settings
title: CADMUS
email: cadmus-dictation.gmail.com
description: "We create wearable devices to assist emergency medical personnel with note-taking during runs to save them time and increase their employer’s margins."


# Team names, titles and social links
people:
- name: Auveed Rokhsaz
  pic: 1
  position: Software Engineer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: Brad Greer
  pic: 2
  position: Electrical Engineer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Mihir Nagaraj
  pic: 3
  position: Mechanical Engineer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: #
  - title: facebook
    url: #
  - title: stack-overflow
    url: #
  - title: bitbucket 
    url: #
  - title: github
    url: http://github.com/CADMUS-Inc

# Postal address (add as many lines as necessary)
address:
  - line: 1106 McMillan St NW
  - line: Atlanta, GA 30318

# Build settings
markdown: kramdown
permalink: pretty
